#!/bin/bash

git submodule update --init --recursive

stow git
stow scripts
stow ssh
stow zsh

if [[ -d "$HOME/.config/Code" ]]
then
    stow vscode
fi

if [[ -d "$HOME/.sdkman" ]]
then
    sdkman_config="$HOME/.sdkman/etc/config"
    if [[ ! -L "$sdkman_config" ]]
    then
        rm "$sdkman_config"
    fi
    stow sdkman
fi

if [[ $(hostname) = lnxsrv* ]]
then
    stow lnxsrv
fi
